version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: zigbee2mqtt_server_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  server:
    image: koenkk/zigbee2mqtt:1.30.1
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0
    ports:
      - 8080
