version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: $APP_MOSQUITTO_IP
      APP_PORT: 1883
      PROXY_AUTH_ADD: "false"

  mosquitto:
    image: eclipse-mosquitto:2.0.15
    volumes:
      - ${APP_DATA_DIR}/data:/mosquitto
      - ${APP_DATA_DIR}/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001   
    networks:
      default:
        ipv4_address: $APP_MOSQUITTO_IP
