version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: ese-mosquitto_server_1
      APP_PORT: 1883
      PROXY_AUTH_ADD: "false"

  server:
    image: eclipse-mosquitto:2.0.17
    volumes:
      - ${APP_DATA_DIR}/data:/mosquitto
      - ${APP_DATA_DIR}/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001   
