version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: $APP_MOSQUITTO_IP
      APP_PORT: 1883
      PROXY_AUTH_ADD: "false"

  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ${APP_DATA_DIR}/data:/mosquitto
      - ${APP_DATA_DIR}/configuration.yaml:/mosquitto/mosquitto.conf
      - ${APP_DATA_DIR}/password.txt:/mosquitto/password.txt
    ports:
      - 1883:1883
      - 9001:9001   
    networks:
      default:
        ipv4_address: $APP_MOSQUITTO_IP
